feat: DialogManager 라우팅
handy-candy/handycandy_client pull request #47
Opened 2021-07-12 10:15 UTC by leahincom

2021-07-12 13:04 UTC, lebmouse requested changes

2021-07-12 13:04 UTC, lebmouse commented on src/components/DialogManager/AddCandy/AddCandyDate.tsx
> +        <>
리턴문 안에 분기가 너무 많아서 읽기가 힘들어
리턴문은 최대한 중첩을 빼는게 좋을듯

```tsx
if(goBefore) return <CandyAdded category={category} selectedCategory={selectedCategory} candy={candy} />
if(added) return <AddCandyMessage category={category} selectedCategory={selectedCategory} candy={candy} />;
return <>...</>

2021-07-12 13:04 UTC, lebmouse commented on src/components/DialogManager/AddCandy/CandyAdded.tsx
> +            <Button text='닫기' size='sm' buttonColor='gray' color='black' onClick={() => setOpenModal(false)} />
해커톤에선 상관없긴한데
이왕이면 인라인함수 쓰는 습관을 안하는게 좋아
많이쓰면 나중에 고치기 귀찮아짐

2021-07-12 13:04 UTC, lebmouse commented on src/components/DialogManager/AddCandy/Dropdown/Category.tsx
> +      {!categoryModal && (
요것도 return문에 분기를 최대한 뺴는게 좋을듯

2021-07-12 13:04 UTC, lebmouse commented on src/components/DialogManager/AddCandy/index.tsx
> +        <>
이렇게 삼항연산자가 하나가 들어가는건 괜찮음, 중복되면 복잡하고 읽기도 힘들어짐,
분기가 if else 가 아니라 길어지면, 아예 분기컴포넌트를 새로 만드는걸 추천함

2021-07-12 13:04 UTC, lebmouse commented on src/components/DialogManager/AddCategory/index.tsx
> +  top: 340px;
요것도 마찬가지로 왼쪽이 고정되어 있으니깐 화면에 따라서 잘 안맞어

2021-07-13 00:35 UTC, leahincom commented on src/components/DialogManager/AddCandy/index.tsx
> +  left: 596px;
wow 마자 ㄱㅅㄱㅅ!!

2021-07-13 00:39 UTC, leahincom commented on src/components/DialogManager/AddCandy/AddCandyDate.tsx
> +        <>
아 그냥 이렇게 나누면 되는구나 나도 적으면서 헷갈렸는데 앞으로 이러케 해야겠당

2021-07-13 03:39 UTC, lebmouse approved these changes

2021-07-13 11:23 UTC, merged